(function(){
  const WORD_NUM={SATU:1,DUA:2,TIGA:3,EMPAT:4,LIMA:5,ENAM:6};
  const META_HEADERS=new Set(['BIL','BIL.','NAMA','NAMA MURID','MYKID','NO. MYKID','NO MYKID','JANTINA','KELAS']);
  function clean(v){return String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();}
  function parseFilename(name){const upper=decodeURIComponent(name).toUpperCase();let year=null,yearWord=null,className='Tidak Diketahui',session=null;const m=upper.match(/TAHUN\s+(SATU|DUA|TIGA|EMPAT|LIMA|ENAM)\s+(.+?)\s+TAHUN\s+(20\d{2})/);if(m){yearWord=m[1];year=WORD_NUM[yearWord];className=clean(m[2]);session=m[3];}return{year,className,session,fileName:name.split('/').pop()};}
  function findHeader(rows){for(let i=0;i<Math.min(rows.length,20);i++){const u=rows[i].map(x=>clean(x).toUpperCase());if(u.some(x=>x==='NAMA'||x.includes('NAMA MURID'))&&u.some(x=>x.includes('MYKID')||x==='JANTINA'))return i;}return -1;}
  function tableRows(doc){const tables=[...doc.querySelectorAll('table')];let best=[];for(const t of tables){const rows=[...t.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>clean(td.textContent)));if(rows.length>best.length)best=rows;}return best;}
  function parseHtml(text,name){const doc=new DOMParser().parseFromString(text,'text/html');const rows=tableRows(doc);const headerIndex=findHeader(rows);if(headerIndex<0)throw new Error('Baris tajuk tidak ditemui');const headers=rows[headerIndex].map(clean);const normalized=headers.map(h=>h.toUpperCase());const nameIndex=normalized.findIndex(h=>h==='NAMA'||h.includes('NAMA MURID'));const subjectIndexes=[];headers.forEach((h,i)=>{const u=h.toUpperCase();if(h&&!META_HEADERS.has(u)&&i>nameIndex)subjectIndexes.push(i);});const students=[];for(const row of rows.slice(headerIndex+1)){const nm=clean(row[nameIndex]);if(!nm||/^(JUMLAH|TOTAL|CATATAN)/i.test(nm))continue;const hasTP=subjectIndexes.some(i=>/^TP\s*[1-6]$/i.test(clean(row[i])));if(!hasTP)continue;const subjectData={};subjectIndexes.forEach(i=>{const val=clean(row[i]).toUpperCase();if(/^TP\s*[1-6]$/.test(val))subjectData[clean(headers[i])]=val.replace(/\s/g,'');});students.push({name:nm,subjects:subjectData});}
    const meta=parseFilename(name);return{...meta,studentCount:students.length,subjects:[...new Set(subjectIndexes.map(i=>clean(headers[i])).filter(Boolean))],students};
  }
  async function parseFile(file){const name=file.name||'fail.xls';const buffer=await file.arrayBuffer();let text;for(const enc of ['utf-8','windows-1252']){try{text=new TextDecoder(enc).decode(buffer);if(text.includes('<table')||text.includes('<html'))break;}catch(e){}}if(!text||(!text.includes('<table')&&!text.includes('<html')))throw new Error('Format fail belum disokong. Gunakan eksport .xls iDME yang asal.');return parseHtml(text,name);}
  window.PBDParser={parseFile,parseHtml,parseFilename};
})();